### ISSUE TITLE
CodersX review

### ISSUE THREAD

**Issue by khoinguyen-corize** [malburo/typing-speed-test#1]
- [x] Chưa tính được CPM (characters per minute)

- [x] Nút **Reset** nên thay bằng **Try again** để nút này ở phía dưới không nên để bên cạnh input

- [x] Không hỗ trợ trên thiết bị di động

- [x] Đoạt footer nên tách ra thành 1 component

- [x] Tên component không được ghi thường như wpm mà phải đổi thành WPM

- [x] Dùng SCSS nhưng lại không phát huy được thế mạnh của nó, vd khai báo biến màu sắc

- [x] Chỗ gọi API bị lặp lại, nên tách ra 1 hàm để xử lý việc gọi API và xử lý response

**Comment by malburo** [comment]
Em fix xong rồi ạ, anh xem giúp em với
